name: Job Configuration workflow

on:
  workflow_dipatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "05 * * 1-5"

jobs:
  build:
    runs-on: unbuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test

      - name: Print a message
        run: echo "Hello, YAML"
