name: Job Configuration workflow

on: 
    push:
        branches: 
            -main 
jobs: 
    build: 
        runs-on: unbuntu-latest

        steps: 
        - name: Check out repository
        - uses: actions/checkout@v2

        - name: Use Node.js 18
        - uses: actions/setup-node@v3
          with: 
            node-version: 18
        - name: Print a message
           run: echo "Hello, YAML"